# Actual release configuration. Requires the executables to be built first (see
# .github/workflows/build.yml).
# Must be renamed to .releaserc.yaml to be used.
branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - assets:
        - path: bootstrap
        - path: executables/*
