#!/usr/bin/env bash

set -euo pipefail

command_exists() {
  type -f "$1" >/dev/null 2>&1
}

case "$OSTYPE" in
  darwin*)
    if ! command_exists brew
    then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    if ! command_exists python3
    then
      brew install python3
    fi

    for PACKAGE in coreutils gnu-tar
    do
      if [ ! -d "/usr/local/opt/$PACKAGE" ]
      then
        brew install "$PACKAGE"
      fi
      PATH="/usr/local/opt/$PACKAGE/libexec/gnubin:$PATH"
    done
 ;;
  linux*)
    DISTRO=$(grep '^ID=' /etc/os-release | cut -d = -f 2)

    ensure() {
      COMMAND="$1"
      shift
      if [ "$#" -ge 1 ]
      then
        PACKAGES=("$@")
      else
        PACKAGES=("$COMMAND")
      fi
      if ! command_exists "$COMMAND"
      then
        if [ "$EUID" -eq 0 ]
        then
          "${INSTALLER[@]}" "${PACKAGES[@]}"
        else
          sudo "${INSTALLER[@]}" "${PACKAGES[@]}"
        fi
      fi
    }

    case $DISTRO in
      debian|ubuntu)
        INSTALLER=(apt install --yes)
        apt update
        ensure git
        ensure sudo
        ensure python3 python3{,-{pip,venv}}
        ensure unzip
        ;;
      fedora)
        INSTALLER=(dnf install --assumeyes)
        ensure bzip2
        ensure xz
        ensure unzip
        ensure chsh util-linux-user
        ;;
    esac
esac

if ! python3 -c 'import pipx' >/dev/null 2>&1
then
  if ! python3 -c 'import pip' >/dev/null 2>&1
  then
    python3 -m ensurepip
  fi
  python3 -m pip install --user pipx
fi

if python3 -m pipx list --short | grep -qE '^mybox ' >/dev/null 2>&1
then
  python3 -m pipx upgrade mybox
else
  python3 -m pipx install mybox
fi
