#!/bin/sh

set -eu

URL="https://github.com/koterpillar/mybox/releases/latest/download/mybox-$(uname -s)-$(uname -m)"
DESTINATION="$HOME/.local/bin/mybox"

if [ -L "$DESTINATION" ]
then
  rm "$DESTINATION"
fi
if ! [ -f "$DESTINATION" ]
then
  mkdir -p "$(dirname "$DESTINATION")"
  touch -t 200001010000 "$DESTINATION"
fi

TEMP_FILE=$(mktemp)
trap 'rm -f "$TEMP_FILE"' EXIT
curl -fsSL "$URL" -z "$DESTINATION" -o "$TEMP_FILE"
if [ -s "$TEMP_FILE" ]
then
  mv "$TEMP_FILE" "$DESTINATION"
  chmod +rx "$DESTINATION"
fi
