ignore:
  - test/Mybox/Spec/Uncovered  # Extra functionality when tests fail, unused when they pass
coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 0%
