#!/usr/bin/env bash
# Install dependencies required for the project

command_exists() {
  type -f "$1" >/dev/null 2>&1
}

case "$OSTYPE" in
  darwin*)
    if ! command_exists brew
    then
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    brew install shellcheck
  ;;
  linux*)
  ;;
esac

if ! command_exists poetry
then
  curl -sSL https://install.python-poetry.org | python3 -
fi

poetry install
