#!/usr/bin/env bash
# Install dependencies required for the project

set -euo pipefail

command_exists() {
  type -f "$1" >/dev/null 2>&1
}

case "$OSTYPE" in
  darwin*)
    if ! command_exists brew
    then
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    if ! command_exists shellcheck
    then
      brew install shellcheck
    fi
  ;;
  linux*)
  ;;
esac

if ! command_exists poetry
then
  pip install poetry
fi

poetry install
