#!/usr/bin/env bash
# Install dependencies required for the project

set -euo pipefail

OPT_LINT="true"
OPT_PYTHON="true"
OPT_HASKELL="true"
while [ $# -gt 0 ]; do
  case "$1" in
    --no-lint)
      OPT_LINT=""
      shift
      ;;
    --no-python)
      OPT_PYTHON=""
      shift
      ;;
    --no-haskell)
      OPT_HASKELL=""
      shift
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

command_exists() {
  type -f "$1" >/dev/null 2>&1
}

sudo_() {
  if [ "$(id -u)" -eq 0 ]
  then
    "$@"
  else
    sudo "$@"
  fi
}

case "$OSTYPE" in
  darwin*)
    if ! command_exists brew
    then
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    if [ -n "${OPT_LINT-}" ] && ! command_exists shellcheck
    then
      brew install shellcheck
    fi
  ;;
  linux*)
    DISTRO=$(grep '^ID=' /etc/os-release | cut -d = -f 2)
    case $DISTRO in
      debian|ubuntu)
        sudo_ apt install --yes liblzma-dev libbz2-dev
        ;;
      fedora)
        sudo_ dnf install --assumeyes xz-devel bzip2-devel
    esac
  ;;
esac

if [ -n "${OPT_PYTHON-}" ] && ! command_exists poetry
then
  pip install poetry
fi

GH_CURL=(curl -fsSL --retry 5)
if [ -n "${GITHUB_TOKEN-}" ]
then
  GH_CURL+=(--header "authorization: Bearer $GITHUB_TOKEN")
elif command_exists gh && gh auth status >/dev/null 2>&1
then
  GH_CURL+=(--header "authorization: Bearer $(gh auth token)")
fi

if [ -n "${OPT_LINT-}" ] && [ -n "${OPT_HASKELL-}" ] && ! command_exists fourmolu
then
  OS=$(echo "$OSTYPE" | sed -E 's/darwin.+/osx/;s/linux.+/linux/')
  ARCH=$(uname -m | sed 's/aarch64/arm64/')

  FILENAME=$(
    "${GH_CURL[@]}" "https://api.github.com/repos/fourmolu/fourmolu/releases/latest" | \
    python3 -c 'import sys,json;[print(a["name"]) for a in json.load(sys.stdin)["assets"]]' | \
    grep "${OS}-${ARCH}"
  )

  if [ -z "$FILENAME" ]
  then
    echo "Error: no fourmolu binary for ${OS}-${ARCH}" >&2
    exit 1
  fi

  mkdir -p ~/.local/bin
  FOURMOLU_URL="https://github.com/fourmolu/fourmolu/releases/latest/download/${FILENAME}"
  "${GH_CURL[@]}" "$FOURMOLU_URL" -o ~/.local/bin/fourmolu
  chmod +x ~/.local/bin/fourmolu
fi

if [ -n "${OPT_PYTHON-}" ]
then
  poetry install
fi
