name: mybox
version: 0.0.1
description: Manage the configuration and tools on your workstation without bothering the OS too much
author: Alexey Kotlyarov <a@koterpillar.com>
maintainer: Alexey Kotlyarov <a@koterpillar.com>
license: GPL-3.0-or-later
language: GHC2021
default-extensions:
  - DerivingVia
  - FunctionalDependencies
  - OverloadedStrings
  - RecordWildCards
  - DuplicateRecordFields
  - OverloadedRecordDot
  # FIXME: all in on record fields? NoFieldSelectors
  - TypeFamilies
  # GHC2024
  - DataKinds
  - DerivingStrategies
  - DisambiguateRecordFields
  - ExplicitNamespaces
  - GADTs
  - LambdaCase
  - MonoLocalBinds
  - RoleAnnotations
dependencies:
  - aeson
  - aeson-extra
  - aeson-jsonpath
  - base
  - base64-bytestring
  - bytestring
  - containers
  - effectful
  - extra
  - Glob
  - mtl
  - network-uri
  - process-extras
  - random
  - safe-exceptions
  - scalpel
  - text
  - vector
  - witherable
  - yaml
ghc-options:
  - -Wall
  - -Werror
  - -threaded
  - -optP-Wno-nonportable-include-path
library:
  source-dirs: src
tests:
  tests:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - bzlib
      - hspec
      - lzma
      - mybox
      - zip-archive
      - zlib
    build-tools:
      - hspec-discover
executables:
  mybox:
    main: Main.hs
    source-dirs: app
    dependencies:
      - mybox
    ghc-options:
      - -rtsopts
      - -with-rtsopts=-N
