name: mybox
version: 0.0.1
description: Manage the configuration and tools on your workstation without bothering the OS too much
author: Alexey Kotlyarov <a@koterpillar.com>
maintainer: Alexey Kotlyarov <a@koterpillar.com>
license: GPL-3.0-or-later
language: GHC2021
default-extensions:
  - FunctionalDependencies
  - OverloadedStrings
  - RecordWildCards
  # GHC2024
  - DataKinds
  - DerivingStrategies
  - DisambiguateRecordFields
  - ExplicitNamespaces
  - GADTs
  - LambdaCase
  - MonoLocalBinds
  - RoleAnnotations
dependencies:
  - base
  - data-has
  - mtl
  - process
  - safe-exceptions
  - text
ghc-options:
  - -Wall
  - -Werror
  - -threaded
  - -optP-Wno-nonportable-include-path
library:
  source-dirs: src
tests:
  tests:
    main: TestMain.hs
    source-dirs:
      - test
    dependencies:
      - mybox
      - tasty
      - tasty-discover
      - tasty-hunit
    build-tools:
      - tasty-discover
executables:
  mybox:
    main: Main.hs
    source-dirs: app
    dependencies:
      - mybox
    ghc-options:
      - -rtsopts
      - -with-rtsopts=-N
