name: mybox
version: 0.0.0
synopsis: Manage the configuration and tools on your workstation without bothering the OS too much
description: See README at <https://github.com/koterpillar/mybox#readme>
maintainer: Alexey Kotlyarov <a@koterpillar.com>
github: koterpillar/mybox
category: Desktop

ghc-options: -Wall

default-extensions:
  - BangPatterns
  - FlexibleInstances
  - FunctionalDependencies
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - RecordWildCards
  - TupleSections
  - TypeApplications

dependencies:
  - base >= 4.9 && < 5

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - mybox

tests:
  spec:
    main: TestMain.hs
    source-dirs: test
    dependencies:
      - mybox
      - tasty
      - tasty-discover
