name: Publish
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: ./install-dev
      - name: Calculate version
        id: tag
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: '^refs/tags/'
          string: ${{ github.ref }}
          replace-with: ''
      - name: Publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry version ${{ steps.tag.outputs.replaced }}
          poetry build
          poetry publish
